services:

  static:
    build: .
    container_name: ${STATIC_CONTAINER_NAME:-static}
    hostname: ${STATIC_HOSTNAME:-static}    
    image: ${STATIC_IMAGE:-static}:${STATIC_VERSION:-latest}
    ports:
      - ${STATIC_PORT:-3232}:80
    volumes:
      - ${STATIC_VOLUMES_VAR:-./var}:/opt/static/var
      - ${STATIC_VOLUMES_SRC:-./src}:/opt/static/src
    restart: unless-stopped
