services:

  static:
    build: .
    container_name: ${STATIC_CONTAINER_NAME:-static}
    hostname: ${STATIC_HOSTNAME:-static}    
    image: ${STATIC_IMAGE:-static}:${STATIC_VERSION:-latest}
    ports:
      - ${STATIC_PORT:-3232}:80
    volumes:
      - ${STATIC_VOLUMES_PUBLIC:-./public}:/opt/static/public
    restart: unless-stopped
